config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:create, :update, :destroy]
  resources :carts, except: [:index, :new, :edit]
  resources :events
  resources :profil_users, only: [:show]
  delete "profil_user_delete" , to: 'profil_users#delete'
  devise_for :users
  resources :pseudo
  root to: "events#index"
  resources :admins 


  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :orders, dependent: :nullify
    belongs_to :user

    validates :title, :description, :price, :city, :zip_code, :start_date, :duration, presence: true
    validates :price, numericality: { greater_than_or_equal_to: 0 }
    validates :title, length: { maximum: 30 }, format: { with: /\A[a-zA-Z\s]+\z/, message: "ne peut contenir que des lettres et des espaces" }
    validates :description, length: { maximum: 250 }, format: { with: /\A[a-zA-Z\s]+\z/, message: "ne peut contenir que des lettres et des espaces" }
    validates :city, length: { maximum: 30 }, format: { with: /\A[a-zA-Z\s]+\z/, message: "ne peut contenir que des lettres et des espaces" }
    validates :duration, numericality: { greater_than: 0 }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  before_action :save_events_in_cart
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :check_event_validation, only: %i[ edit show ]


  # GET /events or /events.json
  def index
    @events = Event.all
    @order = Order.new
    @events_true = Event.where(is_validate: true)
    @events_carrousel = Event.where(is_validate: true).order(created_at: :desc).limit(7)
  end

  # GET /events/1 or /events/1.json
  def show
    @event = Event.find(params[:id])
    @order = Order.new
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events or /events.json
  def create
    all_params_event = event_params.merge(user: current_user)
    @event = Event.new(all_params_event)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: "Evénement créé avec succès" }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Evénement mis à jour" }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Evénement supprimé" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :description, :price, :image_url, :city, :zip_code, :start_date, :duration, :is_validate)
    end

    def check_event_validation
      @event = Event.find(params[:id])
      
      if !@event.is_validate
        flash[:error] = "Cet événement ne peut pas être modifié."
        redirect_to root_path
      end
    end

end

app/helpers/events_helper.rb
module EventsHelper

    def save_events_in_cart
        if current_user != nil
            @events_in_cart = Order.where(cart_id:current_user.cart.id)
        end
    end

end

app/views/events/_banner.html.erb
<%= image_tag("jeu_de_plateau.jpg", alt: "Bienvenue sur lesaventuriersduplateau.fr") %>
  <div class="container-banner text-center mt-2">
  <h1 class="logo_title">LES AVENTURIERS <br> DU PLATEAU</h1>
  <p class= "logo_introduce"><strong> Rejoignez la plus grande communauté de jeux de société en France !</strong> </p>
  <% unless user_signed_in? %>
    <a class="banner-btn" href="<%= new_user_registration_path %>"> Inscrivez-vous ici</a>
  <% end %>
</div>

app/views/events/_carrousel.html.erb
<h2 class="title-section mb-5 text-uppercase">LES NOUVEAUTÉS</h2>
<swiper-container class="mySwiper col-12 col-sm-11 col-md-9 col-xl-8" pagination="false" effect="coverflow" grab-cursor="true" centered-slides="true"
slides-per-view="3" coverflow-effect-rotate="0" coverflow-effect-stretch="0" coverflow-effect-depth="100"
coverflow-effect-modifier="2" coverflow-effect-slide-shadows="false" loop="true">
    <% @events_carrousel.each do |event| %>
    <swiper-slide class="rounded-3">
    <div class="container p-0">
        <img src="<%= event.image_url %>" alt="event image" class="rounded-top-3 img-slider" />
        <div class="d-flex flex-column align-items-center">
        <h3 class="text-center txt-grey title-event text-uppercase pt-3"> <%= event.title%> </h3>
        <a href="<%= event_path(event) %>" class="buttonMore text-decoration-none rounded p-0"><span class="m-0 px-2 fs-6"> Voir plus </span></a>
        </div>
    </div>
    </swiper-slide>
    <% end %>
</swiper-container>

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <h2 class="special-title">Événe<br>ment</h2>
    <div class="container">
        <div class="d-flex justify-content-center row align-items-center">
          <div class="col-11 col-md-5 py-2">  
            <img src=" <%= event.image_url %> " class="img-slider rounded-2 col-12" alt="Image de l'événement">
          </div>
        <div class="event-card d-flex col-10 col-md-5 flex-column align-items-center offset-md-1">
            <h4 class="event-title text">
                <strong>
                    <%= event.title %><p> proposé par : <%= User.find_by(id: event.user_id)&.pseudo %>
                </strong>
            </h4>
            <div class="card-box card mb-3 p-3">
                <div class="row g-0"> 
                    <div class="col-md-8">
                        <div class="card-body">
                            <p>
                                <strong>Description:</strong>
                                <br>
                                <%= event.description %>
                            </p>
                            <div class="info-event">
                                <p>
                                    <strong>Ville:</strong>
                                    <br>
                                    <%= event.city %>, <%= event.zip_code %>
                                </p>
                            </div>
                            <p>
                                <strong>Date:</strong>
                                <br>
                                <%= event.start_date.strftime("%d %B %Y") %>
                            </p>
                            <p>
                                <strong>Durée:</strong>
                                <br>
                                <%= event.duration %> h
                            </p>
                            <p>
                                <strong>Prix:</strong>
                                <br>
                                <%= event.price %> &euro;
                            </p>
                        </div>
                    </div>
                </div>
            </div>
                <% if user_signed_in? %>
                        <%= form_for @order do |f| %>
                        <%= f.hidden_field :event_id, value: @event.id %>
                        <%= f.hidden_field :cart_id, value: current_user.cart.id %>
                        <button type="submit" class="btn validation-button">Ajouter au panier</button>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <ul>
      <li>Veuillez compléter les champs manquants</li>
      <ul>
    </div>
  <% end %>

<div class="form-create-event flex-column align-items-center p-4 rounded-3">
  <div class="py-2 form-group text-center">
    <label for="title" style="display: block" class="form-label">Titre </label>
    <%= form.text_field :title ,class: "form-input rounded-3" %>
  </div>

  <div class="py-2 form-group text-center">
    <label for="description" style="display: block" class="form-label">Description </label>
    <%= form.text_area :description ,class: "form-input rounded-3" %>
  </div>

  <div class="py-2 form-group text-center">
    <label for="image_url" style="display: block" class="form-label">Image <i>(renseigner le lien URL de votre image)</i></label>
    <%= form.text_field :image_url ,class: "form-input rounded-3" %>
  </div>

  <div class="py-2 form-group text-center">
    <label for="city" style="display: block" class="form-label">Ville </label>
    <%= form.text_field :city ,class: "form-input rounded-3" %>
  </div>

  <div class="py-2 form-group text-center">
    <label for="zip_code" style="display: block" class="form-label">Code Postal </label>
    <%= form.text_field :zip_code ,class: "form-input rounded-3" %>
  </div>

  <div class="py-2 form-group text-center">
    <label for="start_date" style="display: block" class="form-label">Date </label>
    <%= form.datetime_field :start_date ,class: "form-input rounded-3 text-center" %>
  </div>

  <div class="py-2 form-group text-center">
    <label for="duration" style="display: block" class="form-label">Durée <i>(en heure)</i></label>
    <%= form.number_field :duration ,class: "form-input rounded-3" %>
  </div>

  <div class="py-2 form-group text-center">
    <label for="price" style="display: block" class="form-label">Prix </label>
    <%= form.number_field :price ,class: "form-input rounded-3"%>
  </div>
  
  <div class="py-3">
   <div style="text-align: center">
    <%= form.submit "Créer l'événement", class: "buttonMore2 py-1" %>
   </div>
  </div>
</div>
<% end %>

app/views/events/_list_event.html.erb
<h2 class="title-section mb-5 text-uppercase">NOS ÉVÉNEMENTS</h2>
<% if user_signed_in? %>

<div style="text-align: center;">
    <p><strong>Devenez le Maître du jeu et créez votre propre événement :</strong></p><br>
</div>
<%= link_to "Créer un événement", new_event_path, class: "bg-green txt-grey text-decoration-none p-2 rounded-2" %>
<% end %>
<div class="d-flex m-5 justify-content-center flex-wrap">
    <% @events_true.each do |event| %>
    <div class="card m-3 col-11 col-md-5 col-xl-3 border-0">
        <img class="card-img-top img-list-event" src=" <%= event.image_url %> " alt="event image">
        <div class="card-body d-flex flex-column justify-content-center align-items-center bg-green">
        <h4 class="card-title"><%= event.title %></h4>
        <p class="card-text "><%= event.price %> €</p>
            <div class="container-fluid d-flex justify-content-center">
            <a href="<%= event_path(event) %>" class="buttonMore text-decoration-none mx-2 p-2">Voir plus</a>
                <% if user_signed_in? %>
                <%= form_for @order do |f| %>
                <%= f.hidden_field :event_id, value: event.id %>
                <%= f.hidden_field :cart_id, value: current_user.cart.id %>
                    <button type="submit" class="buttonMore p-2">Ajouter au panier</button>
                <% end %>
                <% end %>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/events/_presentation.html.erb
<div class="container mt-2">
    <div class="row d-flex align-items-center justify-content-center">
        <img src="https://linote.fr/wp-content/uploads/2022/03/board-games.jpg" class="event-img img-fluid col-11 col-md-4 rounded-5 p-2" alt="Image de présentation">
        <p class="col-12 col-md-6 py-3">Les Aventuriers du plateau est une plateforme qui réunit les principaux événements de jeux de société en France.<br>
        Découvrez les événements organisés près de chez vous, toute l'année selon différentes thématiques. Affrontez des adversaires à Catan dans un tournoi à Toulouse, découvrez le Skyjo chez Jean-Mi avec Amandine et Caroline à Bourges, ou encore profitez d'une après-midi découverte des dernières sorties de jeux à Marseille. 
        </p>
    </div>
    <br>
    <div class="row d-flex align-items-center justify-content-center">
        <p class="col-12 col-md-6 py-3">Découvrez deux types d'organisation sur notre site :<br>
        - Événements par des organismes privés ou associations. Nos premiers événements seront bientôt disponibles.<br>
        - Événements privés créés par des membres de la communauté, chez eux ou dans des lieux publics. Rencontrez d'autres joueurs près de chez vous en cliquant sur "Créer votre événement" et en remplissant le formulaire. Validation requise pour créer un événement.
        </p>
        <img src="https://www.lavenir.net/resizer/ACCeLWKql6jjasnTPbRitOsvfJY=/1200x800/filters:format(jpeg):focal(495x338.5:505x328.5)/cloudfront-eu-central-1.images.arcpublishing.com/ipmgroup/AQD2HZGC6BF3LJLNO4ULITAFBQ.jpg" class="event-img img-fluid col-11 col-md-4 rounded-5 p-2" alt="Image de présentation">
    </div>
</div>



   

app/views/events/edit.html.erb
<h1 class="special-title">Modifier <br>l'événement</h1>

<%= render "form", event: @event %>

<br>

<div style="text-align: center">
  <%= link_to "Voir cet événement", @event %> |
  <%= link_to "Retourner sur les événements", events_path %>
 </div>

app/views/events/index.html.erb
<section class="banner">
  <%= render 'events/banner' %>
  <% if user_signed_in? && current_user.pseudo ==  nil%>
    <div class="container-pseudo d-flex flex-column align-items-center p-1">
      <p class="m-0 text-bolder fs-6"><strong>Bienvenue parmi nous, il est temps de choisir ton pseudo</strong></p>
      <%= form_for(current_user, url: new_pseudo_path, method: :patch, html: { class: 'd-flex align-items-center flex-column flex-sm-row' }) do |f| %>
          <div class="field mx-4">
            <%= f.label :mon_pseudo, class: 'txt-grey' %>
            <%= f.text_field :pseudo, class: 'rounded-2' %>
          </div>   
        <div class="actions my-2">
            <%= f.submit "Mettre à jour le pseudo", class: 'btn-out2' %>
        </div>
      <% end %>
    <% end %>
    <% if user_signed_in? && current_user.pseudo !=  nil%>
      <div style="text-align: center">
        <h3 class="pseudo_title mt-5">Bienvenue à toi <%= current_user.pseudo %> </h3>
      </div>
    </div>
  <% end %>
</section>

<section class="d-flex flex-column justify-content-center align-items-center py-5">
  <%= render 'events/presentation'%>
</section>      
<section class="d-flex flex-column justify-content-center align-items-center py-5">
  <%= render 'events/carrousel' %>
</section>

<section class="d-flex flex-column justify-content-center align-items-center py-5">
  <%= render 'events/list_event' %>
</section>

app/views/events/new.html.erb
<h1 class="special-title">Créer ton<br>événement</h1>
<section class="container py-4">
  <div class="col-8 offset-2 mb-3">
    <%= render "form", event: @event %>
  </div>

  <div>
    <%= link_to "Retour à l'accueil", events_path,class: "text-decoration-none" %>
  </div>
</section>

app/views/events/show.html.erb
<div class="">
      <%= render @event %>
  <div class="py-3 container">
      <% if user_signed_in? && current_user.role === 'admin' %>
        <%= link_to "Corriger l'évènement", edit_event_path(@event) , class: "btn btn-custom txt-blue m-2" %> |
        <%= link_to "Retour aux évènements", events_path , class: "btn btn-custom txt-blue m-2" %>
        <%= button_to "Supprimer", @event, method: :delete, class: "btn btn-custom txt-blue m-2" %>
    <% end %>
  </div>
</div>