config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:create, :update, :destroy]
  resources :carts, except: [:index, :new, :edit]
  resources :events
  resources :profil_users, only: [:show]
  delete "profil_user_delete" , to: 'profil_users#delete'
  devise_for :users
  resources :pseudo
  root to: "events#index"
  resources :admins 


  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :orders, dependent: :nullify
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  include CartsHelper 
  before_action :require_login
  before_action :only_current_cart
  
  def show
    @events_in_cart = Order.where(cart_id:current_user.cart.id)
  end

  def create
  end

  def update
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
  end
end

app/helpers/carts_helper.rb
module CartsHelper
    private

    def require_login
        unless current_user != nil
            redirect_to new_user_session_path
        end
    end

    def only_current_cart
        if current_user != nil && current_user.cart.id != params[:id].to_i
            return redirect_to cart_path(current_user.cart.id)
        end
    end
    
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/destroy.html.erb
<h1>Carts#destroy</h1>
<p>Find me in app/views/carts/destroy.html.erb</p>

app/views/carts/show.html.erb
<h2 class="special-title">MON <br>PANIER</h2>
<div class="container-fluid d-flex justify-content-center align-items-center mt-5">
    <div class="text-card col-11 d-flex justify-content-center">
        <div class="col-12 col-lg-8">
            <dl class="row">
                <% total_price = [] %>
                <% @events_in_cart.each do |event| %>
                <div class="p-4 m-2 container-cart-item">
                    <dt class="col-sm-3">Quantité</dt>
                    <dd class="col-sm-9 text-center"><%= event.quantity %></dd>

                        <hr style="color: #35DE88;">
                    
                    <dl class="row">
                    <dt class="col-sm-3">Nom de l'événement</dt>
                    <dd class="col-sm-6 text-center"><%= event.event.title %></dd>
                    <dd class="col-sm-3">
                        <%= button_to "Supprimer", order_path(event.id), method: :delete, class: 'btn-delete' %>
                    </dd>
                    </dl>

                        <hr style="color: #35DE88;">
                    
                    <dt class="col-sm-3">Prix unitaire</dt>
                    <dd class="col-sm-9 text-center"><%= event.event.price %> €</dd>

                        <hr style="color: #35DE88;">
                    
                    <dt class="col-sm-3">Prix selon quantité</dt>
                    <dd class="col-sm-9 text-center"><%= total_event = event.event.price * event.quantity.to_d %> €</dd>
                    
                    <% total_price << total_event %>
                    
                    <dt class="col-sm-3"></dt>
                    <dd class="col-sm-9"></dd>
                </div>
                <% end %>
                
                <dt class="col-sm-3"></dt>
                <dd class="col-sm-9"></dd>
                
                <dt class="col-sm-3"></dt>
                <dd class="col-sm-9"></dd>
                
                <dt class="col-sm-3 font-weight-bold">Prix total :</dt>
                <dd class="col-sm-9 text-center"><%= total_price.inject(0){|sum,x| sum + x } %> €</dd>
            </dl>
    
    <% if @events_in_cart.any? %>
        <%= button_to "Passer commande", checkout_create_path(total: total_price.inject(0){|sum,x| sum + x }), class: 'btn-order align-items-right', data: {turbo: false} %>
    <% end %>
</div>
</div>
</div>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>